name: schematic
version: 1.0.0+1
publish_to: none
description: SchemaMatic is a web-based application that leverages AI technology to automatically generate dummy data based on user-entered prompts. It is designed to simplify the process of creating mock data for developers, researchers, and other users for testing, development, or simulation purposes.
environment: 
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  get: 4.6.6
  material_design_icons_flutter: 7.0.7296
  intl: ^0.18.0
  loading_animation_widget: ^1.2.0+4
  shimmer: ^3.0.0
  flutter_slidable: ^3.0.0
  dotted_border: ^2.0.0+3
  image_picker: ^1.1.2
  cached_network_image: ^3.2.3
  get_storage: 2.1.1
  google_fonts: 6.2.1
  firebase_core: 3.6.0
  firebase_auth: 5.1.1
  flutter:
    sdk: flutter
  firebase_crashlytics: ^4.0.2
  flutter_launcher_icons: ^0.14.1
  google_generative_ai: ^0.4.6
  flutter_markdown: ^0.7.3+1
  font_awesome_flutter: ^10.7.0
  markdown_widget: ^2.3.2+6
  expandable: ^5.0.1
  url_launcher: ^6.3.0
  firebase_analytics: ^11.1.0
  flutter_dotenv: ^5.1.0
  webview_flutter: ^4.9.0
  firebase_messaging: ^15.0.2
  cloud_firestore: ^5.0.2
  firebase_remote_config: ^5.0.2
  firebase_database: ^11.0.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/lang/
    - .env
  uses-material-design: true


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    # background_color: "#fffff"
    # theme_color: "#fffff"
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/icon.png"